version: "3"
services:
  mongo-auth:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
     - 8081:8081
    volumes: 
      - .docker/auth/data:/data/db
 
  mongo-users:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
     - 8082:8081
    volumes: 
      - .docker/users/data:/data/db

 
  mongo-todos:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
     - 8083:8081
    volumes: 
     - .docker/todos/data:/data/db

  gateway:
    build: ./gateway
    command: npm run start
    volumes:
      - ./gateway:/usr/gateway
      - /usr/gateway/node_modules
    ports:
      - "8000:8000"
  auth:
    build: ./auth
    command: npm run start
    volumes:
      - ./auth:/usr/auth
      - /usr/auth/node_modules
    ports:
      - "8001:8001"
  users:
    build: ./users
    command: npm run start
    volumes:
      - ./users:/usr/users
      - /usr/users/node_modules
    ports:
      - "8002:8002"
  todos:
    build: ./todos
    command: npm run start
    volumes:
      - ./todos:/usr/todos
      - /usr/todos/node_modules
    ports:
      - "8003:8003"
